name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Compile c++
    - uses: uses: rlalik/setup-cpp-compiler@v1.2
    - name: Lint
    - uses: Dal-Papa/actions-uncrustify@v1.2
